apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  APP_KEY: {{ .Values.app.key | quote }}
  DB_PASSWORD: {{ .Values.db.password | default "devpass" | quote }}
  DB_ROOT_PASSWORD: {{ .Values.db.rootPassword | default "rootpass" | quote }}
