apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: laravel-app

helmCharts:
  - name: laravel-app
    repo: file://../../../../../laravel-app
    version: 1.0.0
    releaseName: laravel-app
    namespace: laravel-app
    valuesFile: values.yaml

resources:
  - namespace.yaml
