apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: kubequest
  namespace: argocd
spec:
  description: Projet KubeQuest (Laravel + infrastructure)
  sourceRepos:
    - https://github.com/EpitechMscProPromo2026/T-CLO-902-PAR_5.git
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
