apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: laravel-app-prod

resources:
  - ../../base

patchesStrategicMerge:
  - production-patch.yaml

commonLabels:
  environment: production
