apiVersion: v1
kind: Service
metadata:
  name: opa
  namespace: opa
  labels:
    app.kubernetes.io/name: opa
    app.kubernetes.io/part-of: kubequest
spec:
  selector:
    app: opa
  ports:
    - name: http
      port: 8181
      targetPort: 8181
