apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: laravel-storage-pvc
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.backup.storageClass | default "gp2" }}
