apiVersion: v1
kind: Secret
metadata:
  name: {{ include "laravel-app.fullname" . }}-secrets
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  app-key: {{ .Values.secrets.appKey | quote }}
  db-password: {{ .Values.secrets.dbPassword | quote }}
  redis-password: {{ .Values.secrets.redisPassword | quote }}
  mail-password: {{ .Values.secrets.mailPassword | quote }}
